# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-26 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_belt_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='job',
            name='done_by',
            field=models.IntegerField(default=None),
        ),
    ]
