# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-26 19:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('python_belt_app', '0003_auto_20190826_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='done_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='doing', to='python_belt_app.User'),
        ),
    ]
