# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-26 19:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('python_belt_app', '0005_auto_20190826_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='done_by',
        ),
    ]
